name: pet_connect_app
description: Red social para conectar dueÃ±os de mascotas.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
